language: ruby
rvm:
  - 2.7.0
services:
  - postgresql
env:
  - "RAILS_ENV=test"
before_script:
  - RAILS_ENV=test rake db:create db:migrate
addons:
  postgresql: "9.6"
  code_climate:
    repo_token:
after_success:
  - bundle exec codeclimate-test-reporter
